name: Build

on:
 push:
   branches: [main]
 pull_request:
   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      content: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: Install dependencies
        run: npm ci
      - run: npm run build
      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: npm run deploy
